name: Update gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Commit and push changes
        run: |
          git add ./dist
          git commit -m "Update gh-pages from main branch"
          git push origin gh-pages